apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: sample
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: dharun05/sampleserver:v0.5
          env:
            - name: DB_HOST
              value: "mysql-service.mysql.svc.cluster.local"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "password"
            - name: DB_NAME
              value: "mydb"
            - name: JWT_SECRET
              value: "your_jwt_secret"
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: sample
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP
