version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: password  # root password
      MYSQL_DATABASE: mydb               # name of the database to be created
      # MYSQL_USER: youruser               # non-root user
      # MYSQL_PASSWORD: youruserpassword   # password for the non-root user
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mynetwork

volumes:
  db_data:

networks:
  mynetwork:
    external: true 
